version: "3"

services:
  ccapi-py:
    container_name: ccapi-py
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/market_making_arbitrage/src 
      - ./logs:/market_making_arbitrage/logs 